package mysso.supports.jdbc.serviceprovider.registry.mybatis.dao;

import java.util.List;
import mysso.supports.jdbc.serviceprovider.registry.mybatis.model.ServiceProviderPo;
import mysso.supports.jdbc.serviceprovider.registry.mybatis.model.ServiceProviderPoExample;
import org.apache.ibatis.annotations.Param;

public interface ServiceProviderPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_provider
     *
     * @mbg.generated Wed Sep 27 14:43:08 CST 2017
     */
    long countByExample(ServiceProviderPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_provider
     *
     * @mbg.generated Wed Sep 27 14:43:08 CST 2017
     */
    int deleteByExample(ServiceProviderPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_provider
     *
     * @mbg.generated Wed Sep 27 14:43:08 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_provider
     *
     * @mbg.generated Wed Sep 27 14:43:08 CST 2017
     */
    int insert(ServiceProviderPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_provider
     *
     * @mbg.generated Wed Sep 27 14:43:08 CST 2017
     */
    int insertSelective(ServiceProviderPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_provider
     *
     * @mbg.generated Wed Sep 27 14:43:08 CST 2017
     */
    List<ServiceProviderPo> selectByExample(ServiceProviderPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_provider
     *
     * @mbg.generated Wed Sep 27 14:43:08 CST 2017
     */
    ServiceProviderPo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_provider
     *
     * @mbg.generated Wed Sep 27 14:43:08 CST 2017
     */
    int updateByExampleSelective(@Param("record") ServiceProviderPo record, @Param("example") ServiceProviderPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_provider
     *
     * @mbg.generated Wed Sep 27 14:43:08 CST 2017
     */
    int updateByExample(@Param("record") ServiceProviderPo record, @Param("example") ServiceProviderPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_provider
     *
     * @mbg.generated Wed Sep 27 14:43:08 CST 2017
     */
    int updateByPrimaryKeySelective(ServiceProviderPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_provider
     *
     * @mbg.generated Wed Sep 27 14:43:08 CST 2017
     */
    int updateByPrimaryKey(ServiceProviderPo record);
}